package models;
// Generated 24/11/2017 10:55:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Citas generated by hbm2java
 */
public class Citas  implements java.io.Serializable {


     private Integer idCitasMedicas;
     private Mascota mascota;
     private Persona persona;
     private Date fechaEntrada;
     private Date fechaSalida;
     private String proposito;
     private String observaciones;
     private String tipo;
     private String estado;
     private Set hospitalizacions = new HashSet(0);
     private Set medicamentoses = new HashSet(0);

    public Citas() {
    }

	
    public Citas(Mascota mascota, Persona persona, Date fechaEntrada, Date fechaSalida, String proposito, String tipo, String estado) {
        this.mascota = mascota;
        this.persona = persona;
        this.fechaEntrada = fechaEntrada;
        this.fechaSalida = fechaSalida;
        this.proposito = proposito;
        this.tipo = tipo;
        this.estado = estado;
    }
    public Citas(Mascota mascota, Persona persona, Date fechaEntrada, Date fechaSalida, String proposito, String observaciones, String tipo, String estado, Set hospitalizacions, Set medicamentoses) {
       this.mascota = mascota;
       this.persona = persona;
       this.fechaEntrada = fechaEntrada;
       this.fechaSalida = fechaSalida;
       this.proposito = proposito;
       this.observaciones = observaciones;
       this.tipo = tipo;
       this.estado = estado;
       this.hospitalizacions = hospitalizacions;
       this.medicamentoses = medicamentoses;
    }
   
    public Integer getIdCitasMedicas() {
        return this.idCitasMedicas;
    }
    
    public void setIdCitasMedicas(Integer idCitasMedicas) {
        this.idCitasMedicas = idCitasMedicas;
    }
    public Mascota getMascota() {
        return this.mascota;
    }
    
    public void setMascota(Mascota mascota) {
        this.mascota = mascota;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public String getProposito() {
        return this.proposito;
    }
    
    public void setProposito(String proposito) {
        this.proposito = proposito;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getHospitalizacions() {
        return this.hospitalizacions;
    }
    
    public void setHospitalizacions(Set hospitalizacions) {
        this.hospitalizacions = hospitalizacions;
    }
    public Set getMedicamentoses() {
        return this.medicamentoses;
    }
    
    public void setMedicamentoses(Set medicamentoses) {
        this.medicamentoses = medicamentoses;
    }




}


