package models;
// Generated 23/11/2017 10:21:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hospitalizacion generated by hbm2java
 */
public class Hospitalizacion  implements java.io.Serializable {


     private Integer idHospitalizacion;
     private Citas citas;
     private Mascota mascota;
     private Date fechaSalida;
     private String proposito;
     private String diagnostico;
     private String observaciones;
     private Set medicamentoses = new HashSet(0);
     private Set observacioneses = new HashSet(0);

    public Hospitalizacion() {
    }

	
    public Hospitalizacion(Citas citas, Mascota mascota, String proposito, String diagnostico, String observaciones) {
        this.citas = citas;
        this.mascota = mascota;
        this.proposito = proposito;
        this.diagnostico = diagnostico;
        this.observaciones = observaciones;
    }
    public Hospitalizacion(Citas citas, Mascota mascota, Date fechaSalida, String proposito, String diagnostico, String observaciones, Set medicamentoses, Set observacioneses) {
       this.citas = citas;
       this.mascota = mascota;
       this.fechaSalida = fechaSalida;
       this.proposito = proposito;
       this.diagnostico = diagnostico;
       this.observaciones = observaciones;
       this.medicamentoses = medicamentoses;
       this.observacioneses = observacioneses;
    }
   
    public Integer getIdHospitalizacion() {
        return this.idHospitalizacion;
    }
    
    public void setIdHospitalizacion(Integer idHospitalizacion) {
        this.idHospitalizacion = idHospitalizacion;
    }
    public Citas getCitas() {
        return this.citas;
    }
    
    public void setCitas(Citas citas) {
        this.citas = citas;
    }
    public Mascota getMascota() {
        return this.mascota;
    }
    
    public void setMascota(Mascota mascota) {
        this.mascota = mascota;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public String getProposito() {
        return this.proposito;
    }
    
    public void setProposito(String proposito) {
        this.proposito = proposito;
    }
    public String getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set getMedicamentoses() {
        return this.medicamentoses;
    }
    
    public void setMedicamentoses(Set medicamentoses) {
        this.medicamentoses = medicamentoses;
    }
    public Set getObservacioneses() {
        return this.observacioneses;
    }
    
    public void setObservacioneses(Set observacioneses) {
        this.observacioneses = observacioneses;
    }




}


