package models;
// Generated 17/11/2017 10:10:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mascota generated by hbm2java
 */
public class Mascota  implements java.io.Serializable {


     private Integer idMascotas;
     private Propietario propietario;
     private String nombre;
     private String foto;
     private float peso;
     private float talla;
     private String especie;
     private String raza;
     private String sexo;
     private Date fechaNacimiento;
     private String alimentacion;
     private String medicamentos;
     private String observaciones;
     private String estado;
     private Set citases = new HashSet(0);
     private Set hospitalizacions = new HashSet(0);

    public Mascota() {
    }

	
    public Mascota(Propietario propietario, String nombre, String foto, float peso, float talla, String especie, String raza, String sexo, Date fechaNacimiento, String alimentacion, String estado) {
        this.propietario = propietario;
        this.nombre = nombre;
        this.foto = foto;
        this.peso = peso;
        this.talla = talla;
        this.especie = especie;
        this.raza = raza;
        this.sexo = sexo;
        this.fechaNacimiento = fechaNacimiento;
        this.alimentacion = alimentacion;
        this.estado = estado;
    }
    public Mascota(Propietario propietario, String nombre, String foto, float peso, float talla, String especie, String raza, String sexo, Date fechaNacimiento, String alimentacion, String medicamentos, String observaciones, String estado, Set citases, Set hospitalizacions) {
       this.propietario = propietario;
       this.nombre = nombre;
       this.foto = foto;
       this.peso = peso;
       this.talla = talla;
       this.especie = especie;
       this.raza = raza;
       this.sexo = sexo;
       this.fechaNacimiento = fechaNacimiento;
       this.alimentacion = alimentacion;
       this.medicamentos = medicamentos;
       this.observaciones = observaciones;
       this.estado = estado;
       this.citases = citases;
       this.hospitalizacions = hospitalizacions;
    }
   
    public Integer getIdMascotas() {
        return this.idMascotas;
    }
    
    public void setIdMascotas(Integer idMascotas) {
        this.idMascotas = idMascotas;
    }
    public Propietario getPropietario() {
        return this.propietario;
    }
    
    public void setPropietario(Propietario propietario) {
        this.propietario = propietario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public float getPeso() {
        return this.peso;
    }
    
    public void setPeso(float peso) {
        this.peso = peso;
    }
    public float getTalla() {
        return this.talla;
    }
    
    public void setTalla(float talla) {
        this.talla = talla;
    }
    public String getEspecie() {
        return this.especie;
    }
    
    public void setEspecie(String especie) {
        this.especie = especie;
    }
    public String getRaza() {
        return this.raza;
    }
    
    public void setRaza(String raza) {
        this.raza = raza;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getAlimentacion() {
        return this.alimentacion;
    }
    
    public void setAlimentacion(String alimentacion) {
        this.alimentacion = alimentacion;
    }
    public String getMedicamentos() {
        return this.medicamentos;
    }
    
    public void setMedicamentos(String medicamentos) {
        this.medicamentos = medicamentos;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getCitases() {
        return this.citases;
    }
    
    public void setCitases(Set citases) {
        this.citases = citases;
    }
    public Set getHospitalizacions() {
        return this.hospitalizacions;
    }
    
    public void setHospitalizacions(Set hospitalizacions) {
        this.hospitalizacions = hospitalizacions;
    }




}


