package models;
// Generated 24/11/2017 10:55:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mascota generated by hbm2java
 */
public class Mascota  implements java.io.Serializable {


     private Integer idMascotas;
     private Propietario propietario;
     private String nombre;
     private String foto;
     private float peso;
     private int condicionCorporal;
     private String color;
     private String especie;
     private String raza;
     private String genero;
     private Date fechaNacimiento;
     private String alimentacion;
     private String medicamentos;
     private String observaciones;
     private String estado;
     private Set citases = new HashSet(0);
     private Set hospitalizacions = new HashSet(0);

    public Mascota() {
    }

	
    public Mascota(Propietario propietario, String nombre, String foto, float peso, int condicionCorporal, String color, String especie, String raza, String genero, Date fechaNacimiento, String alimentacion, String estado) {
        this.propietario = propietario;
        this.nombre = nombre;
        this.foto = foto;
        this.peso = peso;
        this.condicionCorporal = condicionCorporal;
        this.color = color;
        this.especie = especie;
        this.raza = raza;
        this.genero = genero;
        this.fechaNacimiento = fechaNacimiento;
        this.alimentacion = alimentacion;
        this.estado = estado;
    }
    public Mascota(Propietario propietario, String nombre, String foto, float peso, int condicionCorporal, String color, String especie, String raza, String genero, Date fechaNacimiento, String alimentacion, String medicamentos, String observaciones, String estado, Set citases, Set hospitalizacions) {
       this.propietario = propietario;
       this.nombre = nombre;
       this.foto = foto;
       this.peso = peso;
       this.condicionCorporal = condicionCorporal;
       this.color = color;
       this.especie = especie;
       this.raza = raza;
       this.genero = genero;
       this.fechaNacimiento = fechaNacimiento;
       this.alimentacion = alimentacion;
       this.medicamentos = medicamentos;
       this.observaciones = observaciones;
       this.estado = estado;
       this.citases = citases;
       this.hospitalizacions = hospitalizacions;
    }
   
    public Integer getIdMascotas() {
        return this.idMascotas;
    }
    
    public void setIdMascotas(Integer idMascotas) {
        this.idMascotas = idMascotas;
    }
    public Propietario getPropietario() {
        return this.propietario;
    }
    
    public void setPropietario(Propietario propietario) {
        this.propietario = propietario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public float getPeso() {
        return this.peso;
    }
    
    public void setPeso(float peso) {
        this.peso = peso;
    }
    public int getCondicionCorporal() {
        return this.condicionCorporal;
    }
    
    public void setCondicionCorporal(int condicionCorporal) {
        this.condicionCorporal = condicionCorporal;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getEspecie() {
        return this.especie;
    }
    
    public void setEspecie(String especie) {
        this.especie = especie;
    }
    public String getRaza() {
        return this.raza;
    }
    
    public void setRaza(String raza) {
        this.raza = raza;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getAlimentacion() {
        return this.alimentacion;
    }
    
    public void setAlimentacion(String alimentacion) {
        this.alimentacion = alimentacion;
    }
    public String getMedicamentos() {
        return this.medicamentos;
    }
    
    public void setMedicamentos(String medicamentos) {
        this.medicamentos = medicamentos;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getCitases() {
        return this.citases;
    }
    
    public void setCitases(Set citases) {
        this.citases = citases;
    }
    public Set getHospitalizacions() {
        return this.hospitalizacions;
    }
    
    public void setHospitalizacions(Set hospitalizacions) {
        this.hospitalizacions = hospitalizacions;
    }




}


