package models;
// Generated 17/11/2017 09:31:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Medicamentos generated by hbm2java
 */
public class Medicamentos  implements java.io.Serializable {


     private Integer idMedicamento;
     private Citas citas;
     private Hospitalizacion hospitalizacion;
     private Persona persona;
     private String nombre;
     private String laboratorio;
     private String lote;
     private Date fecha;

    public Medicamentos() {
    }

	
    public Medicamentos(Persona persona, String nombre, String laboratorio, String lote, Date fecha) {
        this.persona = persona;
        this.nombre = nombre;
        this.laboratorio = laboratorio;
        this.lote = lote;
        this.fecha = fecha;
    }
    public Medicamentos(Citas citas, Hospitalizacion hospitalizacion, Persona persona, String nombre, String laboratorio, String lote, Date fecha) {
       this.citas = citas;
       this.hospitalizacion = hospitalizacion;
       this.persona = persona;
       this.nombre = nombre;
       this.laboratorio = laboratorio;
       this.lote = lote;
       this.fecha = fecha;
    }
   
    public Integer getIdMedicamento() {
        return this.idMedicamento;
    }
    
    public void setIdMedicamento(Integer idMedicamento) {
        this.idMedicamento = idMedicamento;
    }
    public Citas getCitas() {
        return this.citas;
    }
    
    public void setCitas(Citas citas) {
        this.citas = citas;
    }
    public Hospitalizacion getHospitalizacion() {
        return this.hospitalizacion;
    }
    
    public void setHospitalizacion(Hospitalizacion hospitalizacion) {
        this.hospitalizacion = hospitalizacion;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLaboratorio() {
        return this.laboratorio;
    }
    
    public void setLaboratorio(String laboratorio) {
        this.laboratorio = laboratorio;
    }
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


