package models;
// Generated 23/11/2017 10:21:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idVeterinario;
     private long documento;
     private String nombres;
     private String apellidos;
     private String genero;
     private long telefono;
     private String correo;
     private String direccion;
     private String ciudad;
     private String perfil;
     private String especialidad;
     private String foto;
     private String contrasena;
     private String estado;
     private Set observacioneses = new HashSet(0);
     private Set citases = new HashSet(0);
     private Set medicamentoses = new HashSet(0);

    public Persona() {
    }

	
    public Persona(long documento, String nombres, String apellidos, String genero, long telefono, String correo, String direccion, String ciudad, String perfil, String foto, String contrasena, String estado) {
        this.documento = documento;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.genero = genero;
        this.telefono = telefono;
        this.correo = correo;
        this.direccion = direccion;
        this.ciudad = ciudad;
        this.perfil = perfil;
        this.foto = foto;
        this.contrasena = contrasena;
        this.estado = estado;
    }
    public Persona(long documento, String nombres, String apellidos, String genero, long telefono, String correo, String direccion, String ciudad, String perfil, String especialidad, String foto, String contrasena, String estado, Set observacioneses, Set citases, Set medicamentoses) {
       this.documento = documento;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.genero = genero;
       this.telefono = telefono;
       this.correo = correo;
       this.direccion = direccion;
       this.ciudad = ciudad;
       this.perfil = perfil;
       this.especialidad = especialidad;
       this.foto = foto;
       this.contrasena = contrasena;
       this.estado = estado;
       this.observacioneses = observacioneses;
       this.citases = citases;
       this.medicamentoses = medicamentoses;
    }
   
    public Integer getIdVeterinario() {
        return this.idVeterinario;
    }
    
    public void setIdVeterinario(Integer idVeterinario) {
        this.idVeterinario = idVeterinario;
    }
    public long getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(long documento) {
        this.documento = documento;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(long telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getObservacioneses() {
        return this.observacioneses;
    }
    
    public void setObservacioneses(Set observacioneses) {
        this.observacioneses = observacioneses;
    }
    public Set getCitases() {
        return this.citases;
    }
    
    public void setCitases(Set citases) {
        this.citases = citases;
    }
    public Set getMedicamentoses() {
        return this.medicamentoses;
    }
    
    public void setMedicamentoses(Set medicamentoses) {
        this.medicamentoses = medicamentoses;
    }




}


