package models;
// Generated 15/11/2017 02:18:11 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Medicamentos generated by hbm2java
 */
public class Medicamentos  implements java.io.Serializable {


     private Integer idMedicamento;
     private Citas citas;
     private Hospitalizacion hospitalizacion;
     private Veterinario veterinario;
     private String nombre;
     private String laboratorio;
     private String lote;
     private Date fecha;

    public Medicamentos() {
    }

	
    public Medicamentos(Veterinario veterinario, String nombre, String laboratorio, String lote, Date fecha) {
        this.veterinario = veterinario;
        this.nombre = nombre;
        this.laboratorio = laboratorio;
        this.lote = lote;
        this.fecha = fecha;
    }
    public Medicamentos(Citas citas, Hospitalizacion hospitalizacion, Veterinario veterinario, String nombre, String laboratorio, String lote, Date fecha) {
       this.citas = citas;
       this.hospitalizacion = hospitalizacion;
       this.veterinario = veterinario;
       this.nombre = nombre;
       this.laboratorio = laboratorio;
       this.lote = lote;
       this.fecha = fecha;
    }
   
    public Integer getIdMedicamento() {
        return this.idMedicamento;
    }
    
    public void setIdMedicamento(Integer idMedicamento) {
        this.idMedicamento = idMedicamento;
    }
    public Citas getCitas() {
        return this.citas;
    }
    
    public void setCitas(Citas citas) {
        this.citas = citas;
    }
    public Hospitalizacion getHospitalizacion() {
        return this.hospitalizacion;
    }
    
    public void setHospitalizacion(Hospitalizacion hospitalizacion) {
        this.hospitalizacion = hospitalizacion;
    }
    public Veterinario getVeterinario() {
        return this.veterinario;
    }
    
    public void setVeterinario(Veterinario veterinario) {
        this.veterinario = veterinario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLaboratorio() {
        return this.laboratorio;
    }
    
    public void setLaboratorio(String laboratorio) {
        this.laboratorio = laboratorio;
    }
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


