package models;
// Generated 15/11/2017 02:18:11 PM by Hibernate Tools 4.3.1



/**
 * Observaciones generated by hbm2java
 */
public class Observaciones  implements java.io.Serializable {


     private Integer idObservaciones;
     private Hospitalizacion hospitalizacion;
     private Veterinario veterinario;
     private String observacionDiaria;

    public Observaciones() {
    }

    public Observaciones(Hospitalizacion hospitalizacion, Veterinario veterinario, String observacionDiaria) {
       this.hospitalizacion = hospitalizacion;
       this.veterinario = veterinario;
       this.observacionDiaria = observacionDiaria;
    }
   
    public Integer getIdObservaciones() {
        return this.idObservaciones;
    }
    
    public void setIdObservaciones(Integer idObservaciones) {
        this.idObservaciones = idObservaciones;
    }
    public Hospitalizacion getHospitalizacion() {
        return this.hospitalizacion;
    }
    
    public void setHospitalizacion(Hospitalizacion hospitalizacion) {
        this.hospitalizacion = hospitalizacion;
    }
    public Veterinario getVeterinario() {
        return this.veterinario;
    }
    
    public void setVeterinario(Veterinario veterinario) {
        this.veterinario = veterinario;
    }
    public String getObservacionDiaria() {
        return this.observacionDiaria;
    }
    
    public void setObservacionDiaria(String observacionDiaria) {
        this.observacionDiaria = observacionDiaria;
    }




}


