package models;
// Generated 15/11/2017 02:18:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Veterinario generated by hbm2java
 */
public class Veterinario  implements java.io.Serializable {


     private Integer idVeterinario;
     private Date fechaNacimiento;
     private long documento;
     private String nombres;
     private String apellidos;
     private String genero;
     private long telefono;
     private String direccion;
     private String ciudad;
     private String especialidad;
     private String foto;
     private String contrasena;
     private String estado;
     private Set citases = new HashSet(0);
     private Set observacioneses = new HashSet(0);
     private Set medicamentoses = new HashSet(0);

    public Veterinario() {
    }

	
    public Veterinario(Date fechaNacimiento, long documento, String nombres, String apellidos, String genero, long telefono, String direccion, String ciudad, String especialidad, String foto, String contrasena, String estado) {
        this.fechaNacimiento = fechaNacimiento;
        this.documento = documento;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.genero = genero;
        this.telefono = telefono;
        this.direccion = direccion;
        this.ciudad = ciudad;
        this.especialidad = especialidad;
        this.foto = foto;
        this.contrasena = contrasena;
        this.estado = estado;
    }
    public Veterinario(Date fechaNacimiento, long documento, String nombres, String apellidos, String genero, long telefono, String direccion, String ciudad, String especialidad, String foto, String contrasena, String estado, Set citases, Set observacioneses, Set medicamentoses) {
       this.fechaNacimiento = fechaNacimiento;
       this.documento = documento;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.genero = genero;
       this.telefono = telefono;
       this.direccion = direccion;
       this.ciudad = ciudad;
       this.especialidad = especialidad;
       this.foto = foto;
       this.contrasena = contrasena;
       this.estado = estado;
       this.citases = citases;
       this.observacioneses = observacioneses;
       this.medicamentoses = medicamentoses;
    }
   
    public Integer getIdVeterinario() {
        return this.idVeterinario;
    }
    
    public void setIdVeterinario(Integer idVeterinario) {
        this.idVeterinario = idVeterinario;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public long getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(long documento) {
        this.documento = documento;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(long telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getCitases() {
        return this.citases;
    }
    
    public void setCitases(Set citases) {
        this.citases = citases;
    }
    public Set getObservacioneses() {
        return this.observacioneses;
    }
    
    public void setObservacioneses(Set observacioneses) {
        this.observacioneses = observacioneses;
    }
    public Set getMedicamentoses() {
        return this.medicamentoses;
    }
    
    public void setMedicamentoses(Set medicamentoses) {
        this.medicamentoses = medicamentoses;
    }




}


